In [54]:
import numpy as np
import pandas as pd

In [55]:
df = pd.read_csv('customer.csv')

In [56]:
df.sample(5)

age  gender   review education purchased
30   73    Male  Average        UG        No
41   23    Male     Good        PG       Yes
4    16  Female  Average        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No

In [57]:
df = df.iloc[:,2:]

In [58]:
df.head(5)

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [59]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [60]:
X_train

review education
16     Poor        UG
2      Good        PG
26     Poor        PG
40     Good    School
39     Poor        PG
41     Good        PG
6      Good    School
30  Average        UG
37  Average        PG
20  Average    School
48     Good        UG
44  Average        UG
34  Average    School
35     Poor    School
33     Good        PG
42     Good        PG
8   Average        UG
0   Average    School
9      Good        UG
14     Poor        PG
17     Poor        UG
12     Poor    School
22     Poor        PG
36     Good        UG
4   Average        UG
11     Good        UG
38     Good    School
7      Poor    School
24  Average        PG
49     Good        UG
29  Average        UG
25     Good    School
32  Average        UG
23     Good    School
1      Poor        UG
13  Average    School
28     Poor    School
45     Poor        PG
10     Good        UG
43     Poor        PG

In [61]:
oe = OrdinalEncoder(
    categories=[['Poor','Average','Good'], ['School', 'UG', 'PG']]  #0 , 1 , 2
)

In [75]:
X_train_encoded = oe.fit_transform(X_train)
X_test_encoded = oe.transform(X_test)

In [63]:
X_train_encoded

array([[0., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.]])

In [76]:
X_test_encoded

array([[0., 2.],
       [1., 0.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [2., 2.]])

In [65]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [71]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [72]:
y_test

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0])

In [73]:
y_train

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [74]:
le.classes_

array(['No', 'Yes'], dtype=object)