In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
X, y = load_iris(return_X_y=True)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [4]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [5]:
import numpy as np

(X_train - np.mean(X_train, axis=0))/np.std(X_train, axis=0)

array([[-0.2121268 ,  1.62335219, -1.18571343, -1.19484829],
       [ 0.03621677, -0.1699943 ,  0.2399941 ,  0.37074001],
       [-0.2121268 , -0.39416261,  0.2399941 ,  0.10980862],
       [-1.20550107, -1.51500417, -0.27326061, -0.28158845],
       [-1.57801642,  1.17501556, -1.58491154, -1.32531399],
       [-0.33629858, -0.39416261, -0.10217571,  0.10980862],
       [-0.33629858, -0.84249924,  0.2399941 ,  0.10980862],
       [ 0.28456034, -0.1699943 ,  0.46810731,  0.24027432],
       [ 0.53290391, -1.73917248,  0.3540507 ,  0.10980862],
       [ 1.02959104,  0.50251063,  1.09541862,  1.67539692],
       [ 0.78124747, -0.1699943 ,  0.98136202,  0.76213708],
       [-0.9571575 , -1.29083586, -0.44434551, -0.15112276],
       [ 0.40873212, -1.96334079,  0.41107901,  0.37074001],
       [-1.32967285,  0.05417401, -1.24274173, -1.32531399],
       [-1.45384464,  0.27834232, -1.24274173, -1.32531399],
       [ 0.65707569,  0.27834232,  0.41107901,  0.37074001],
       [ 0.65707569,  0.

In [6]:
X_train_scaled

array([[-0.2121268 ,  1.62335219, -1.18571343, -1.19484829],
       [ 0.03621677, -0.1699943 ,  0.2399941 ,  0.37074001],
       [-0.2121268 , -0.39416261,  0.2399941 ,  0.10980862],
       [-1.20550107, -1.51500417, -0.27326061, -0.28158845],
       [-1.57801642,  1.17501556, -1.58491154, -1.32531399],
       [-0.33629858, -0.39416261, -0.10217571,  0.10980862],
       [-0.33629858, -0.84249924,  0.2399941 ,  0.10980862],
       [ 0.28456034, -0.1699943 ,  0.46810731,  0.24027432],
       [ 0.53290391, -1.73917248,  0.3540507 ,  0.10980862],
       [ 1.02959104,  0.50251063,  1.09541862,  1.67539692],
       [ 0.78124747, -0.1699943 ,  0.98136202,  0.76213708],
       [-0.9571575 , -1.29083586, -0.44434551, -0.15112276],
       [ 0.40873212, -1.96334079,  0.41107901,  0.37074001],
       [-1.32967285,  0.05417401, -1.24274173, -1.32531399],
       [-1.45384464,  0.27834232, -1.24274173, -1.32531399],
       [ 0.65707569,  0.27834232,  0.41107901,  0.37074001],
       [ 0.65707569,  0.

In [7]:
from sklearn.preprocessing import MinMaxScaler #min=0, max =1, No negatives
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
X_train_scaled

array([[0.37142857, 0.75      , 0.11864407, 0.08333333],
       [0.42857143, 0.41666667, 0.54237288, 0.58333333],
       [0.37142857, 0.375     , 0.54237288, 0.5       ],
       [0.14285714, 0.16666667, 0.38983051, 0.375     ],
       [0.05714286, 0.66666667, 0.        , 0.04166667],
       [0.34285714, 0.375     , 0.44067797, 0.5       ],
       [0.34285714, 0.29166667, 0.54237288, 0.5       ],
       [0.48571429, 0.41666667, 0.61016949, 0.54166667],
       [0.54285714, 0.125     , 0.57627119, 0.5       ],
       [0.65714286, 0.54166667, 0.79661017, 1.        ],
       [0.6       , 0.41666667, 0.76271186, 0.70833333],
       [0.2       , 0.20833333, 0.33898305, 0.41666667],
       [0.51428571, 0.08333333, 0.59322034, 0.58333333],
       [0.11428571, 0.45833333, 0.10169492, 0.04166667],
       [0.08571429, 0.5       , 0.10169492, 0.04166667],
       [0.57142857, 0.5       , 0.59322034, 0.58333333],
       [0.57142857, 0.45833333, 0.76271186, 0.70833333],
       [0.94285714, 0.75      ,

In [10]:
X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis=0)

(X_train - X_min) / (X_max - X_min)


array([[0.37142857, 0.75      , 0.11864407, 0.08333333],
       [0.42857143, 0.41666667, 0.54237288, 0.58333333],
       [0.37142857, 0.375     , 0.54237288, 0.5       ],
       [0.14285714, 0.16666667, 0.38983051, 0.375     ],
       [0.05714286, 0.66666667, 0.        , 0.04166667],
       [0.34285714, 0.375     , 0.44067797, 0.5       ],
       [0.34285714, 0.29166667, 0.54237288, 0.5       ],
       [0.48571429, 0.41666667, 0.61016949, 0.54166667],
       [0.54285714, 0.125     , 0.57627119, 0.5       ],
       [0.65714286, 0.54166667, 0.79661017, 1.        ],
       [0.6       , 0.41666667, 0.76271186, 0.70833333],
       [0.2       , 0.20833333, 0.33898305, 0.41666667],
       [0.51428571, 0.08333333, 0.59322034, 0.58333333],
       [0.11428571, 0.45833333, 0.10169492, 0.04166667],
       [0.08571429, 0.5       , 0.10169492, 0.04166667],
       [0.57142857, 0.5       , 0.59322034, 0.58333333],
       [0.57142857, 0.45833333, 0.76271186, 0.70833333],
       [0.94285714, 0.75      ,